"""Make entry image_path nullable

Revision ID: 0ef6efaf1d4a
Revises: 0001_initial
Create Date: 2026-02-16 22:51:59.084826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef6efaf1d4a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attention_entries', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index('ix_attention_entries_report_id', table_name='attention_entries')
    op.drop_index('ix_classrooms_school_id', table_name='classrooms')
    op.drop_index('ix_lesson_reports_class_id', table_name='lesson_reports')
    op.drop_index('ix_lesson_reports_lesson_date', table_name='lesson_reports')
    op.drop_index('ix_lesson_reports_school_id', table_name='lesson_reports')
    op.drop_index('ix_students_class_id', table_name='students')
    op.alter_column('unrecognized_entries', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_index('ix_unrecognized_entries_report_id', table_name='unrecognized_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unrecognized_entries_report_id', 'unrecognized_entries', ['report_id'], unique=False)
    op.alter_column('unrecognized_entries', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_index('ix_students_class_id', 'students', ['class_id'], unique=False)
    op.create_index('ix_lesson_reports_school_id', 'lesson_reports', ['school_id'], unique=False)
    op.create_index('ix_lesson_reports_lesson_date', 'lesson_reports', ['lesson_date'], unique=False)
    op.create_index('ix_lesson_reports_class_id', 'lesson_reports', ['class_id'], unique=False)
    op.create_index('ix_classrooms_school_id', 'classrooms', ['school_id'], unique=False)
    op.create_index('ix_attention_entries_report_id', 'attention_entries', ['report_id'], unique=False)
    op.alter_column('attention_entries', 'image_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
